### PR TITLE
Travis-ci testing, fixes for Python 3 and various Django versions

### PR DESCRIPTION
**Pull request by PetrDlouhy**
This PR makes tests working in Django versions 1.5-1.8, in Python 2.7 and 3.4
Test results for my repository are at https://travis-ci.org/PetrDlouhy/django-author/builds/90102460

Tests for the main repository will have to be enabled.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Wow, it's great thanks!

May I ask you a favor? While I don't really maintain this plugin, I would like to make you a collaborator of this plugin. So let me know if you are interested in :-)

Anyway thanks for the PR :-)

**Comment by lambdalisue** [comment]
I modify `setup.py` and update PyPI version :-)

**Comment by PetrDlouhy** [comment]
OK, make me a collaborator.

**Comment by lambdalisue** [comment]
Done. Now you are collaborator :-)

**Comment by PetrDlouhy** [comment]
@lambdalisue I can't enable Travis-ci testing even if I am colaborator. Can you do it please? You have to log on the Travis-ci with your Github account, then go to https://travis-ci.org/profile/lambdalisue and set the project to enabled.

**Comment by lambdalisue** [comment]
True. I turned on so it will be called from next commit :-)

**Comment by lambdalisue** [comment]
I added budge and the initial test success :clap: 
https://travis-ci.org/lambdalisue/django-author

**Pull request merged**
